excluded:
- Pods
- WeatherForecast/AppLifeCycle
- WeatherForecast/Model
- WeatherForecast/NetworkLayer/ServerModel

disabled_rules:
- trailing_whitespace
- identifier_name
- line_length

opt_in_rules:
- toggle_bool
- multiline_function_chains
- weak_delegate
- private_action
- private_outlet
- fatal_error_message
